spring:
  application:
    name: fluss
  threads:
    virtual:
      enabled: true
  cloud:
    stream:
      bindings:
        eineAktenQuelle-out-0:
          destination: stromschnellen
        einAktenFluss-in-0:
          destination: stromschnellen
          group: akten-fluss-gruppe
        einAktenFluss-out-0:
          destination: stromschnellen

      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}
    function:
      definition: eineAktenQuelle;einAktenFluss
